### ISSUE TITLE
Remove exif data from images

### ISSUE THREAD

**Issue by ghost** [EndeavourOS-Community-Editions/Community-wallpapers#10]
Removing exif data from images is important for security I think. I checked photos from community and there is a lot of exif data in it. So I can not use community wallpapers because of that. I will very appreciate it images not have exif datas.

**Comment by killajoe** [comment]
isn't this more an issue for the one providing the image than using it?  
Or we talk about possible malicious code in exif data?

**Comment by killajoe** [comment]
i mean no problem we can remove the data, exiftool should be able to do that .. 
Only i do not see the issue aside from the opposite that the one providing a picture have data like coordinates used device.

**Comment by ghost** [comment]
While git was downloading, I saw 1409 items downloading. I thought there were so many wallpapers (and I thought they were increasing day by day). That is why I opened the issue—to make this a standard. I didn't check the whole repo. There are 30 or fewer wallpapers, and I didn't check them all. It is my fault. Sorry. Also, thank you for making this distro awesome!
