### ISSUE TITLE
New background image - Cassini Nova

### ISSUE THREAD

**Issue by GiorgioReale** [EndeavourOS-Community-Editions/Community-wallpapers#8]
Reading the latest [news](https://endeavouros.com/news/cassini-nova-with-some-necessary-bugfixes-is-available/) from the official EndeavourOS [site](https://endeavouros.com/) in which the release of Cassini Nova was announced i noticed a new background image that is not available in this repo.
Is it possible to add this image in this repository?

![image](https://user-images.githubusercontent.com/77497498/224579412-3159d35e-fb6c-4bba-9306-377335ba6be0.png)

**Comment by killajoe** [comment]
i can add it ;)

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/Community-wallpapers/commit/e4d848d9258748b447332c1e39d1820e798ed860
